### PR TITLE
Initialize the styles more lazily

### LINKED ISSUE #3239: Crash when looking at trajectories without having looked at a window since the process was started
How I encountered this problem: 
Create a flight plan for a current loaded craft in space; (maneuver showed in navball)
Save the game;
Exit KSP and Restart;
Continue the game and immediately load the saved file;
Press M, game froze for seconds and crash.

If I delete the flight plan then press M, I can continue game.

### PR DESCRIPTION
**Pull request by eggrobin**
Fix #3239.

### CODE REVIEW

File: ksp_plugin_adapter/style.cs [hunk 1]
```diff
@@ -96,8 +97,8 @@ internal static class Style {
   // It is very important to use *static* styles for these elements.  If we use
```
Comment (pleroy) [inline ksp_plugin_adapter/style.cs:97]: Fix the comment now that the styles are not static.

Comment (eggrobin) [reply ksp_plugin_adapter/style.cs:97]: The styles are still static.
