### PR TITLE
Use ThreadPool instead of Bundle in integrator_plots.cpp.

### LINKED ISSUE #4431: Thread overflow in Bundle
EDIT: the actual issue is with `Bundle` (see https://github.com/mockingbirdnest/Principia/issues/4431#issuecomment-3881796404).

The logging backend should still be updated at some point, but it doesn't seem to be causing any actual trouble.

### Original post
I tried to run ErrorAnalysisTest.DISABLED_IntegratorPlots and it crashed, so I ran with `-fsanitizer=thread` and got some warnings:

```
WARNING: ThreadSanitizer: data race (pid=45797)
  Write of size 4 at 0x000100971434 by thread T5:
    #0 principia::mathematica::_integrator_plots::internal::WorkErrorGraphGenerator<principia::quantities::_quantities::internal::Quantity<principia::quantities::_dimensions::internal::Dimensions<2ll, 1ll, -2ll, 0ll, 0ll, 0ll, 0ll, 0ll>>>::Integrate(int, int) integrator_plots.cpp:446 (error_analysis_test:x86_64+0x10036ad3d)
    #1 std::__1::__function::__func<std::__1::__bind<absl::Status (principia::mathematica::_integrator_plots::internal::WorkErrorGraphGenerator<principia::quantities::_quantities::internal::Quantity<principia::quantities::_dimensions::internal::Dimensions<2ll, 1ll, -2ll, 0ll, 0ll, 0ll, 0ll, 0ll>>>::*)(int, int), principia::mathematica::_integrator_plots::internal::WorkErrorGraphGenerator<principia::quantities::_quantities::internal::Quantity<principia::quantities::_dimensions::internal::Dimensions<2ll, 1ll, -2ll, 0ll, 0ll, 0ll, 0ll, 0ll>>>*, long long&, long long&>, std::__1::allocator<std::__1::__bind<absl::Status (principia::mathematica::_integrator_plots::internal::WorkErrorGraphGenerator<principia::quantities::_quantities::internal::Quantity<principia::quantities::_dimensions::internal::Dimensions<2ll, 1ll, -2ll, 0ll, 0ll, 0ll, 0ll, 0ll>>>::*)(int, int), principia::mathematica::_integrator_plots::internal::WorkErrorGraphGenerator<principia::quantities::_quantities::internal::Quantity<principia::quantities::_dimensions::internal::Dimensions<2ll, 1ll, -2ll, 0ll, 0ll, 0ll, 0ll, 0ll>>>*, long long&, long long&>>, absl::Status ()>::operator()() function.h:319 (error_analysis_test:x86_64+0x10036fd68)
    #2 principia::base::_bundle::internal::Bundle::Toil(std::__1::function<absl::Status ()> const&) bundle.cpp:57 (error_analysis_test:x86_64+0x1005dc22b)

  Previous write of size 4 at 0x000100971434 by thread T6:
    #0 principia::mathematica::_integrator_plots::internal::WorkErrorGraphGenerator<principia::quantities::_quantities::internal::Quantity<principia::quantities::_dimensions::internal::Dimensions<2ll, 1ll, -2ll, 0ll, 0ll, 0ll, 0ll, 0ll>>>::Integrate(int, int) integrator_plots.cpp:446 (error_analysis_test:x86_64+0x10036ad3d)
    #1 std::__1::__function::__func<std::__1::__bind<absl::Status (principia::mathematica::_integrator_plots::internal::WorkErrorGraphGenerator<principia::quantities::_quantities::internal::Quantity<principia::quantities::_dimensions::internal::Dimensions<2ll, 1ll, -2ll, 0ll, 0ll, 0ll, 0ll, 0ll>>>::*)(int, int), principia::mathematica::_integrator_plots::internal::WorkErrorGraphGenerator<principia::quantities::_quantities::internal::Quantity<principia::quantities::_dimensions::internal::Dimensions<2ll, 1ll, -2ll, 0ll, 0ll, 0ll, 0ll, 0ll>>>*, long long&, long long&>, std::__1::allocator<std::__1::__bind<absl::Status (principia::mathematica::_integrator_plots::internal::WorkErrorGraphGenerator<principia::quantities::_quantities::internal::Quantity<principia::quantities::_dimensions::internal::Dimensions<2ll, 1ll, -2ll, 0ll, 0ll, 0ll, 0ll, 0ll>>>::*)(int, int), principia::mathematica::_integrator_plots::internal::WorkErrorGraphGenerator<principia::quantities::_quantities::internal::Quantity<principia::quantities::_dimensions::internal::Dimensions<2ll, 1ll, -2ll, 0ll, 0ll, 0ll, 0ll, 0ll>>>*, long long&, long long&>>, absl::Status ()>::operator()() function.h:319 (error_analysis_test:x86_64+0x10036fd68)
    #2 principia::base::_bundle::internal::Bundle::Toil(std::__1::function<absl::Status ()> const&) bundle.cpp:57 (error_analysis_test:x86_64+0x1005dc22b)
```

There are similar warnings for the other `SolveWith*Step` calls in the switch statement.

I'm not really sure what's going wrong here; I don't see any writes there.

### PR DESCRIPTION
**Pull request by rnlahaye**
#4440.

Fixes #4431.

### CODE REVIEW

File: mathematica/integrator_plots.cpp [hunk 1]
```diff
@@ -315,21 +315,27 @@ class WorkErrorGraphGenerator {
   }
 
   std::string GetMathematicaData() {
-    LOG(INFO) << "Using " << std::thread::hardware_concurrency()
-              << " worker threads";
```
Comment (eggrobin) [inline mathematica/integrator_plots.cpp:319]: I was wondering why we had this log (which was incorrect, but now becomes correct again). It turns out that the bundle used to have a limit on its thread count and a queue, and that was changed in https://github.com/mockingbirdnest/Principia/pull/2031. (I am not sure what annoyed us enough to change it; I think the tests were very brittle.)

EDIT: Ah, #2031 is mentioned as part of the Trappist-1 issue; that is probably the explanation.

Comment (pleroy) [reply mathematica/integrator_plots.cpp:319]: I suspect that we ran into contention when running on a machine with 64 cores.  If the functions are short enough, that queue is going to be expensive to manage.
