### PR TITLE
Fix a couple of bugs in flight plan rebasing

### LINKED ISSUE #2655: Flight plan rebase preserves plan duration instead of plan end time
Pretty much exactly what the title says. The first screenshot is before rebase and the second one is after rebase.

Screenshot (7)

Screenshot (8)

In my opinion, extending the flight plan beyond the time it was supposed to end isn't useful. All the extra computation and rendering can actually be detrimental to gameplay.

### LINKED ISSUE #2658: Rebasing a flight plan when past the end fatals the game.
Create a flight plan, warp time forwards until the flight plan is entirely in the past, click rebase.
Game crashes with a fatal:
`    @   00007FFE341663EF  	google::LogMessageFatal::~LogMessageFatal [0x00007FFE341663EE+46] (C:\Users\Richard\Documents\GitHub\Principia-build\Google\glog\src\logging.cc:2109)
    @   00007FFDDAEE4211  	principia::ksp_plugin::internal_flight_plan::FlightPlan::FlightPlan [0x00007FFDDAEE4210+432] (C:\Users\Richard\Documents\GitHub\Principia-build\Principia\ksp_plugin\flight_plan.cpp:63)
    @   00007FFDDB0D0A5D  	principia::ksp_plugin::internal_vessel::Vessel::CreateFlightPlan [0x00007FFDDB0D0A5C+268] (C:\Users\Richard\Documents\GitHub\Principia-build\Principia\ksp_plugin\vessel.cpp:295)
    @   00007FFDDB0D2E5A  	principia::ksp_plugin::internal_vessel::Vessel::RebaseFlightPlan [0x00007FFDDB0D2E59+601] (C:\Users\Richard\Documents\GitHub\Principia-build\Principia\ksp_plugin\vessel.cpp:325)
    @   00007FFDDAF71047  	principia__FlightPlanRebase [0x00007FFDDAF71046+486] (C:\Users\Richard\Documents\GitHub\Principia-build\Principia\ksp_plugin\interface_flight_plan.cpp:352)
    @   000001FAF67C759D  	(No symbol) [0x000001FAF67C759C]
F0730 15:36:56.331396  2140 flight_plan.cpp:63] Check failed: desired_final_time_ >= initial_time_ 
`

### PR DESCRIPTION
**Pull request by eggrobin**
- Fix #2655;
- fix #2658.

### CODE REVIEW

File: ksp_plugin/vessel.cpp [hunk 1]
```diff
@@ -323,7 +323,10 @@ Status Vessel::RebaseFlightPlan(Mass const& initial_mass) {
   not_null<std::unique_ptr<FlightPlan>> const original_flight_plan =
       std::move(flight_plan_);
   CreateFlightPlan(
-      original_flight_plan->desired_final_time(),
+      new_initial_time >= original_flight_plan->desired_final_time()
+          ? new_initial_time + (original_flight_plan->desired_final_time() -
+                                original_flight_plan->initial_time())
+          : original_flight_plan->desired_final_time(),
```
Comment (pleroy) [inline ksp_plugin/vessel.cpp:329]: Invest in a variable to give a name to this complicated expression.
