### PR TITLE
Fix pairs in loops

### LINKED ISSUE #603: Range-based for loops over maps
The `range-declaration` should declare a variable named `pair`.
The elements of `pair` used in the loop should be named, using `auto`.

### PR DESCRIPTION
**Pull request by pleroy**
Fix #603.

### CODE REVIEW

File: ksp_plugin_test/plugin_test.cpp [hunk 1]
```diff
@@ -147,28 +147,30 @@ class TestablePlugin : public Plugin {
     std::vector<not_null<std::unique_ptr<MassiveBody const>>> bodies;
     std::vector<DegreesOfFreedom<Barycentric>> initial_state;
     auto bodies_it = absolute_initialization_->bodies.begin();
-    for (auto const& index_state : absolute_initialization_->initial_state) {
-      EXPECT_EQ(index_state.first, bodies_it->first);
+    for (auto const& pair : absolute_initialization_->initial_state) {
+      Index const index = pair.first;
+      auto const& degree_of_freedom = pair.second;
+      EXPECT_EQ(pair.first, bodies_it->first);
```
Comment (eggrobin) [inline ksp_plugin_test/plugin_test.cpp]: `s/pair\.first/index/
