### PR TITLE
Fix a crash when crashing a vessel into another

### LINKED ISSUE #1553: Fatal error when a decoupling results in a destructive collision
Present in Чебышёв, see #1552.
I have a journal at 5bddb355403cd2a3b4892ffbb6d65ceb55520870.

### PR DESCRIPTION
**Pull request by eggrobin**
Fix #1553.

### CODE REVIEW

File: journal/player_test.cpp [hunk 1]
```diff
@@ -106,23 +106,21 @@ TEST_F(PlayerTest, DISABLED_Debug) {
   LOG(ERROR) << "Last successful method out/return: \n"
               << player.last_method_out_return().DebugString();
 
-#if 0
+#if 1
```
Comment (pleroy) [inline journal/player_test.cpp]: Revert.

File: journal/player_test.cpp [hunk 2]
```diff
@@ -106,23 +106,21 @@ TEST_F(PlayerTest, DISABLED_Debug) {
...
   {
     auto* extension = method_out_return.MutableExtension(
-        serialization::AdvanceTime::extension);
+        serialization::CatchUpLaggingVessels::extension);
   }
   LOG(ERROR) << "Running unpaired method:\n" << method_in.DebugString();
-  CHECK(RunIfAppropriate<AdvanceTime>(method_in,
+  CHECK(RunIfAppropriate<CatchUpLaggingVessels>(method_in,
                                       method_out_return,
                                       player));
```
Comment (pleroy) [inline journal/player_test.cpp]: Bad indent.

File: ksp_plugin/pile_up.cpp [hunk 3]
```diff
@@ -249,12 +250,19 @@ PileUp::PileUp(
...
+}
+
 void PileUp::DeformPileUpIfNeeded() {
   if (apparent_part_degrees_of_freedom_.empty()) {
     return;
   }
   // A consistency check that |SetPartApparentDegreesOfFreedom| was called for
   // all the parts.
+  // TODO(egg): I'd like to log some useful information on check failure, but I
+  // need clean way of getting the debug strings of all parts (rather than giant
```
Comment (pleroy) [inline ksp_plugin/pile_up.cpp]: "a clean"?
