### PR TITLE
Proper usage of the multiset container

### LINKED ISSUE #2159: Check failure in the protector
No journal; I was investigating another issue when this happened.
```
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
    @   00007FFBCB7A86B0  	principia::physics::internal_ephemeris::Ephemeris<principia::geometry::internal_frame::Frame<enum principia::serialization::Frame_PluginTag,7,1> >::Guard::~Guard [0x00007FFBCB7A86AF+31] (c:\users\robin\projects\mockingbirdnest\principia\physics\ephemeris_body.hpp:817)
    @   00007FFBA238FDC0  	principia::ksp_plugin::internal_vessel::Vessel::FlowPrognostication [0x00007FFBA238FDBF+1279] (c:\users\robin\projects\mockingbirdnest\principia\ksp_plugin\vessel.cpp:526)
    @   00007FFBA2391CB2  	principia::ksp_plugin::internal_vessel::Vessel::RepeatedlyFlowPrognostication [0x00007FFBA2391CB1+865] (c:\users\robin\projects\mockingbirdnest\principia\ksp_plugin\vessel.cpp:477)
    @   00007FFBA238699C  	std::_LaunchPad<std::unique_ptr<std::tuple<std::_Binder<std::_Unforced,void (__cdecl principia::base::ThreadPool<principia::base::Status>::*)(void),principia::base::ThreadPool<principia::base::Status> *> >,std::default_delete<std::tuple<std::_Binder<std:: [0x00007FFBA238699B+107] (c:\program files (x86)\microsoft visual studio\preview\community\vc\tools\msvc\14.15.26608\include\thr\xthread:230)
    @   00007FFBA231D099  	std::_Pad::_Call_func [0x00007FFBA231D098+8] (c:\program files (x86)\microsoft visual studio\preview\community\vc\tools\msvc\14.15.26608\include\thr\xthread:208)
    @   00007FFC0A23E3FE  	o_strcat_s [0x00007FFC0A23E3FD+93]
    @   00007FFC0B9D4034  	BaseThreadInitThunk [0x00007FFC0B9D4033+19]
    @   00007FFC0D433691  	RtlUserThreadStart [0x00007FFC0D433690+32]
F0511 12:22:45.519395 17088 protector.cpp:33] Check failed: 1 == protection_start_times_.erase(t_min) (1 vs. 2) 
```
Decoded stack trace:
 https://github.com/mockingbirdnest/Principia/blob/039b5e8f63ce6659f06ff84529e8b14a6bd526a1/ksp_plugin/vessel.cpp#L452-L477  https://github.com/mockingbirdnest/Principia/blob/039b5e8f63ce6659f06ff84529e8b14a6bd526a1/ksp_plugin/vessel.cpp#L492-L526  https://github.com/mockingbirdnest/Principia/blob/039b5e8f63ce6659f06ff84529e8b14a6bd526a1/physics/ephemeris_body.hpp#L816-L817

https://github.com/mockingbirdnest/Principia/blob/039b5e8f63ce6659f06ff84529e8b14a6bd526a1/physics/protector.cpp#L29-L33

### PR DESCRIPTION
**Pull request by pleroy**
Fix #2159.

### CODE REVIEW

File: physics/protector.cpp [hunk 1]
```diff
@@ -30,7 +30,9 @@ void Protector::Unprotect(Instant const& t_min) {
   std::vector<Callback> callbacks_to_run;
   {
     absl::MutexLock l(&lock_);
-    CHECK_EQ(1, protection_start_times_.erase(t_min));
+    auto const it = protection_start_times_.find(t_min);
+    CHECK(it != protection_start_times_.end());
```
Comment (eggrobin) [inline physics/protector.cpp]: Should this log `t_min`?
