### PR TITLE
Linux tolerances

### LINKED ISSUE #1009: Test failures on Linux
```
physics/ephemeris_test.cpp:451: Failure
Value of: probe_positions.size()
Expected: is equal to 476
  Actual: 534 (of type unsigned long)
physics/ephemeris_test.cpp:453: Failure
Value of: probe_positions.back().coordinates().x
Expected: is within 259 to 259 ULPs of -3.05377490234148093e+07 m
  Actual: -3.05377490234158151e+07 m, the numbers are separated by 270 ULPs
[  FAILED  ] EphemerisTest.EarthProbe (2 ms)
```
```
physics/ephemeris_test.cpp:1128: Failure
Value of: time - *previous_time
Expected: is within 118 to 1665 ULPs of +1.05340131194971308e+08 s
  Actual: +1.05340131194940329e+08 s, the numbers are separated by 2079 ULPs
physics/ephemeris_test.cpp:1152: Failure
Value of: time - *previous_time
Expected: is within 103 to 2779 ULPs of +5.26700655974856541e+07 s
  Actual: +5.26700655974590778e+07 s, the numbers are separated by 3567 ULPs
physics/ephemeris_test.cpp:1152: Failure
Value of: time - *previous_time
Expected: is within 103 to 2779 ULPs of +5.26700655974856541e+07 s
  Actual: +5.26700655975086689e+07 s, the numbers are separated by 3089 ULPs
[  FAILED  ] EphemerisTest.ComputeApsides (109 ms)
```
```
[  FAILED  ] 2 tests, listed below:
[  FAILED  ] EphemerisTest.EarthProbe
[  FAILED  ] EphemerisTest.ComputeApsides
```
The discrepancy in `probe_positions.size()` is very weird.

### PR DESCRIPTION
**Pull request by pleroy**
Fix #1009.

### CODE REVIEW

File: physics/ephemeris_test.cpp [hunk 1]
```diff
@@ -448,9 +449,11 @@ TEST_F(EphemerisTest, EarthProbe) {
     probe_positions.push_back(it.degrees_of_freedom().position() -
                               ICRFJ2000Equator::origin);
   }
-  EXPECT_THAT(probe_positions.size(), Eq(476));
+  // The problem is stiff, so different compilers result in different errors and
```
Comment (eggrobin) [inline physics/ephemeris_test.cpp]: It's a straight line at constant velocity, how is that stiff?
