### PR TITLE
Guard the ephemeris as soon as we construct the prognosticator parameters

### LINKED ISSUE #2165: Crash when warping at high speed with short history
`F0511 20:11:52.193073  4916 continuous_trajectory_body.hpp:173] Check failed: t_min_locked() <= time (+4.28789530227277544e+05 s vs. +4.27813530227277544e+05 s)`
Stack:
```
    @   000007FED18D915B  	principia::physics::internal_ephemeris::Ephemeris<principia::geometry::internal_frame::Frame<enum principia::serialization::Frame_PluginTag,7,1> >::ComputeGravitationalAccelerationByMassiveBodyOnMasslessBodies<0> [0x000007FED18D915A+90] (c:\users\phl\projects\github\principia\principia\physics\ephemeris_body.hpp:1016)
    @   000007FED196E670  	principia::physics::internal_ephemeris::Ephemeris<principia::geometry::internal_frame::Frame<enum principia::serialization::Frame_PluginTag,7,1> >::ComputeMasslessBodiesGravitationalAccelerations [0x000007FED196E66F+447] (c:\users\phl\projects\github\principia\principia\physics\ephemeris_body.hpp:1121)
    @   000007FED190F409  	<lambda_238bcc44e5612def8e4e635268f83d36>::operator() [0x000007FED190F408+72] (c:\users\phl\projects\github\principia\principia\physics\ephemeris_body.hpp:471)
    @   000007FED19DE4BC  	std::_Func_impl_no_alloc<<lambda_238bcc44e5612def8e4e635268f83d36>,principia::base::Status,principia::geometry::internal_point::Point<principia::quantities::internal_quantities::Quantity<principia::quantities::internal_dimensions::Dimensions<0,0,1,0,0,0,0 [0x000007FED19DE4BB+27] (c:\program files (x86)\microsoft visual studio\preview\enterprise\vc\tools\msvc\14.16.27023\include\functional:16707566)
    @   000007FED22CFF8E  	principia::integrators::internal_embedded_explicit_runge_kutta_nyström_integrator::EmbeddedExplicitRungeKuttaNyströmIntegrator<principia::integrators::methods::Dormand???????Prince1986RKN434FM,principia::geometry::internal_point::Point<principia::geometry [0x000007FED22CFF8D+1933] (c:\users\phl\projects\github\principia\principia\integrators\embedded_explicit_runge_kutta_nyström_integrator_body.hpp:190)
    @   000007FED18E07E4  	principia::physics::internal_ephemeris::Ephemeris<principia::geometry::internal_frame::Frame<enum principia::serialization::Frame_PluginTag,7,1> >::FlowODEWithAdaptiveStep<principia::integrators::internal_ordinary_differential_equations::SpecialSecondOrde [0x000007FED18E07E3+2163] (c:\users\phl\projects\github\principia\principia\physics\ephemeris_body.hpp:1199)
    @   000007FED1979262  	principia::physics::internal_ephemeris::Ephemeris<principia::geometry::internal_frame::Frame<enum principia::serialization::Frame_PluginTag,7,1> >::FlowWithAdaptiveStep [0x000007FED1979261+161] (c:\users\phl\projects\github\principia\principia\physics\ephemeris_body.hpp:481)
    @   000007FED239AB12  	principia::ksp_plugin::internal_vessel::Vessel::FlowPrognostication [0x000007FED239AB11+321] (c:\users\phl\projects\github\principia\principia\ksp_plugin\vessel.cpp:504)
    @   000007FED239CDBC  	principia::ksp_plugin::internal_vessel::Vessel::RepeatedlyFlowPrognostication [0x000007FED239CDBB+843] (c:\users\phl\projects\github\principia\principia\ksp_plugin\vessel.cpp:477)
    @   000007FED2391BCC  	std::_LaunchPad<std::unique_ptr<std::tuple<std::_Binder<std::_Unforced,void (__cdecl principia::base::ThreadPool<principia::base::Status>::*)(void),principia::base::ThreadPool<principia::base::Status> *> >,std::default_delete<std::tuple<std::_Binder<std:: [0x000007FED2391BCB+107] (c:\program files (x86)\microsoft visual studio\preview\enterprise\vc\tools\msvc\14.16.27023\include\thr\xthread:230)
    @   000007FED2327129  	std::_Pad::_Call_func [0x000007FED2327128+8] (c:\program files (x86)\microsoft visual studio\preview\enterprise\vc\tools\msvc\14.16.27023\include\thr\xthread:208)
    @   000007FED954CD70  	o__realloc_base [0x000007FED954CD6F+95]
    @   00000000771C555D  	BaseThreadInitThunk [0x00000000771C555C+12]
    @   000000007742385D  	RtlUserThreadStart [0x000000007742385C+28]
```
It seems that the parameters passed to the prognosticator have a `first_time` which is before the `t_min` protected by the guard.

Decoded stack trace:
 https://github.com/mockingbirdnest/Principia/blob/493ff14bc042f8b54218bfc71dd7d6c1e0b3251b/ksp_plugin/vessel.cpp#L452-L477  https://github.com/mockingbirdnest/Principia/blob/493ff14bc042f8b54218bfc71dd7d6c1e0b3251b/ksp_plugin/vessel.cpp#L492-L504  https://github.com/mockingbirdnest/Principia/blob/493ff14bc042f8b54218bfc71dd7d6c1e0b3251b/physics/ephemeris_body.hpp#L465-L481  https://github.com/mockingbirdnest/Principia/blob/493ff14bc042f8b54218bfc71dd7d6c1e0b3251b/physics/ephemeris_body.hpp#L1139-L1199  https://github.com/mockingbirdnest/Principia/blob/493ff14bc042f8b54218bfc71dd7d6c1e0b3251b/integrators/embedded_explicit_runge_kutta_nystr%C3%B6m_integrator_body.hpp#L46-L190  https://github.com/mockingbirdnest/Principia/blob/493ff14bc042f8b54218bfc71dd7d6c1e0b3251b/physics/ephemeris_body.hpp#L469-L471  https://github.com/mockingbirdnest/Principia/blob/493ff14bc042f8b54218bfc71dd7d6c1e0b3251b/physics/ephemeris_body.hpp#L1100-L1121  https://github.com/mockingbirdnest/Principia/blob/493ff14bc042f8b54218bfc71dd7d6c1e0b3251b/physics/ephemeris_body.hpp#L1012-L1016

https://github.com/mockingbirdnest/Principia/blob/493ff14bc042f8b54218bfc71dd7d6c1e0b3251b/physics/continuous_trajectory_body.hpp#L169-L173

### PR DESCRIPTION
**Pull request by pleroy**
Fix #2165.

### CODE REVIEW

File: ksp_plugin/vessel.cpp [hunk 1]
```diff
@@ -442,60 +462,50 @@ Vessel::Vessel()
...
+      SwapPrognostication(prognostication, status);
     }
 
     std::this_thread::sleep_until(wakeup_time);
   }
 }
 
 Status Vessel::FlowPrognostication(
-    PrognosticatorParameters const& prognosticator_parameters,
+    PrognosticatorParameters&& prognosticator_parameters,
```
Comment (eggrobin) [inline ksp_plugin/vessel.cpp]: https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rf-consume

> Flag all `X&&` parameters (where `X` is not a template type parameter name) where the function body uses them without `std::move`.

🚩

File: ksp_plugin/vessel.cpp [hunk 2]
```diff
@@ -286,15 +292,29 @@ void Vessel::DeleteFlightPlan() {
...
 void Vessel::RefreshPrediction() {
   absl::MutexLock l(&prognosticator_lock_);
+  // The guard below ensures that the ephemeris will not be "forgotten before"
+  // the end of the psychohistory between now and the time when the
+  // prognosticator finishes the integration.  This ensures that the ephemeris'
+  // |t_min| is never after the time that |FlowWithAdaptiveStep| tries to
+  // integrate.
+  // The guard will be destroyed either when the next set of parameters is
+  // created or when the prognostication has been computed.
+  // Note that we know that |RefreshPrediction| is called on the main thread and
```
[the remark this answers is not in the document]
Comment (pleroy) [reply ksp_plugin/vessel.cpp]: Done.

File: ksp_plugin/vessel.cpp (hunk 1 above)
Comment (pleroy) [reply ksp_plugin/vessel.cpp]: Done.
