### PR TITLE
Statically link the UCRT

### LINKED ISSUE #4188: PluginCompatibilityTest.Reach fails with Windows 11 24H2
See also #4182, #4183, #4184 (and the diurnal tests are still failing).

Note: last time we broke the Reach test, it was FMA: https://github.com/mockingbirdnest/Principia/pull/3979.

### PR DESCRIPTION
**Pull request by eggrobin**
And pin it at 10.0.22621 (Windows 11 22H2), which is before before 10.0.26100 (Windows 11 24H2).
(There is no Windows 11 SDK for 10.0.22631, Windows 11 23H2).

Fix #4188.

This also gets rid of the separate glog.dll, libprotobuf.dll, and serialization.dll, which had been introduced in #1686.

### CODE REVIEW

File: ksp_plugin_test/flight_plan_optimizer_test.cpp [hunk 1]
```diff
@@ -201,7 +201,7 @@ class FlightPlanOptimizerTest : public testing::Test {
   }
 
   std::unique_ptr<Plugin const> plugin_;
-  FlightPlan* flight_plan_ = nullptr;
+  FlightPlan* flight_plan_;
```
Comment (pleroy) [inline ksp_plugin_test/flight_plan_optimizer_test.cpp:204]: Let's keep this.

File: ksp_plugin_test/flight_plan_optimizer_test.cpp [hunk 2]
```diff
@@ -230,52 +226,47 @@ TEST_F(FlightPlanOptimizerTest, DISABLED_ReachTheMoon) {
   // basically goes through the centre of the Moon.
 
   LOG(INFO) << "Optimizing manœuvre 5";
-  auto const& manœuvre5 = flight_plan_->GetManœuvre(5);
+  auto const manœuvre5 = flight_plan_->GetManœuvre(5);
```
Comment (pleroy) [inline ksp_plugin_test/flight_plan_optimizer_test.cpp:229]: And this.

File: ksp_plugin_test/flight_plan_optimizer_test.cpp [hunk 3]
```diff
@@ -230,52 +226,47 @@ TEST_F(FlightPlanOptimizerTest, DISABLED_ReachTheMoon) {
...
+      (manœuvre5.Δv() - flight_plan_->GetManœuvre(5).Δv()).Norm(),
+      IsNear(1.054_(1) * Metre / Second));
+  EXPECT_EQ(113, number_of_evaluations);
   number_of_evaluations = 0;
 
   CHECK_OK(flight_plan_->Replace(manœuvre5.burn(), /*index=*/5));
 
   LOG(INFO) << "Optimizing manœuvre 6";
-  auto const& manœuvre6 = flight_plan_->GetManœuvre(6);
+  auto const manœuvre6 = flight_plan_->GetManœuvre(6);
```
Comment (pleroy) [inline ksp_plugin_test/flight_plan_optimizer_test.cpp:246]: And this.

File: ksp_plugin_test/flight_plan_optimizer_test.cpp [hunk 4]
```diff
@@ -230,52 +226,47 @@ TEST_F(FlightPlanOptimizerTest, DISABLED_ReachTheMoon) {
...
+  EXPECT_THAT((manœuvre6.Δv() - flight_plan_->GetManœuvre(6).Δv()).Norm(),
+              IsNear(1.292_(1) * Metre / Second));
+  EXPECT_EQ(124, number_of_evaluations);
   number_of_evaluations = 0;
 
   CHECK_OK(flight_plan_->Replace(manœuvre6.burn(), /*index=*/6));
 
   LOG(INFO) << "Optimizing manœuvre 7";
-  auto const& manœuvre7 = flight_plan_->GetManœuvre(7);
+  auto const manœuvre7 = flight_plan_->GetManœuvre(7);
```
Comment (pleroy) [inline ksp_plugin_test/flight_plan_optimizer_test.cpp:262]: And this.

File: ksp_plugin_test/flight_plan_optimizer_test.cpp [hunk 5]
```diff
@@ -309,74 +296,57 @@ TEST_F(FlightPlanOptimizerTest, DISABLED_GrazeTheMoon) {
       [&number_of_evaluations](FlightPlan const&) { ++number_of_evaluations; });
 
   LOG(INFO) << "Optimizing manœuvre 5";
-  auto const& manœuvre5 = flight_plan_->GetManœuvre(5);
+  auto const manœuvre5 = flight_plan_->GetManœuvre(5);
```
Comment (pleroy) [inline ksp_plugin_test/flight_plan_optimizer_test.cpp:299]: And this.

File: ksp_plugin_test/flight_plan_optimizer_test.cpp [hunk 6]
```diff
@@ -309,74 +296,57 @@ TEST_F(FlightPlanOptimizerTest, DISABLED_GrazeTheMoon) {
...
+  EXPECT_THAT(flyby_time, ResultOf(&TTSecond, "1972-03-27T01:24:00"_DateTime));
+  EXPECT_THAT(flyby_distance, IsNear(2255.3_(1) * Kilo(Metre)));
   EXPECT_EQ(79, number_of_evaluations);
   number_of_evaluations = 0;
 
   CHECK_OK(flight_plan_->Replace(manœuvre5.burn(), /*index=*/5));
 
   LOG(INFO) << "Optimizing manœuvre 6";
-  auto const& manœuvre6 = flight_plan_->GetManœuvre(6);
+  auto const manœuvre6 = flight_plan_->GetManœuvre(6);
```
Comment (pleroy) [inline ksp_plugin_test/flight_plan_optimizer_test.cpp:318]: And this.

File: ksp_plugin_test/flight_plan_optimizer_test.cpp [hunk 7]
```diff
@@ -309,74 +296,57 @@ TEST_F(FlightPlanOptimizerTest, DISABLED_GrazeTheMoon) {
...
+  EXPECT_THAT(flyby_time, ResultOf(&TTSecond, "1972-03-27T01:16:41"_DateTime));
+  EXPECT_THAT(flyby_distance, IsNear(2001.4_(1) * Kilo(Metre)));
+  EXPECT_EQ(72, number_of_evaluations);
   number_of_evaluations = 0;
 
   CHECK_OK(flight_plan_->Replace(manœuvre6.burn(), /*index=*/6));
 
   LOG(INFO) << "Optimizing manœuvre 7";
-  auto const& manœuvre7 = flight_plan_->GetManœuvre(7);
+  auto const manœuvre7 = flight_plan_->GetManœuvre(7);
```
Comment (pleroy) [inline ksp_plugin_test/flight_plan_optimizer_test.cpp:336]: And this.

File: ksp_plugin_test/flight_plan_optimizer_test.cpp [hunk 8]
```diff
@@ -392,7 +362,7 @@ TEST_F(FlightPlanOptimizerTest, DISABLED_GrindsToAHalt) {
       [&number_of_evaluations](FlightPlan const&) { ++number_of_evaluations; });
 
   LOG(INFO) << "Optimizing manœuvre 5";
-  auto const& manœuvre5 = flight_plan_->GetManœuvre(5);
+  auto const manœuvre5 = flight_plan_->GetManœuvre(5);
```
Comment (pleroy) [inline ksp_plugin_test/flight_plan_optimizer_test.cpp:365]: And this.

File: ksp_plugin_test/flight_plan_optimizer_test.cpp [hunk 9]
```diff
@@ -434,70 +400,57 @@ TEST_F(FlightPlanOptimizerTest, DISABLED_PoleTheMoon) {
...
```
Comment (pleroy) [inline ksp_plugin_test/flight_plan_optimizer_test.cpp:403]: And this.

File: ksp_plugin_test/flight_plan_optimizer_test.cpp [hunk 10]
```diff
@@ -434,70 +400,57 @@ TEST_F(FlightPlanOptimizerTest, DISABLED_PoleTheMoon) {
...
+  EXPECT_THAT(flyby_time, ResultOf(&TTSecond, "1972-03-27T01:09:20"_DateTime));
   EXPECT_THAT(flyby_inclination, IsNear(90.23_(1) * Degree));
   EXPECT_EQ(25, number_of_evaluations);
   number_of_evaluations = 0;
 
   CHECK_OK(flight_plan_->Replace(manœuvre5.burn(), /*index=*/5));
 
   LOG(INFO) << "Optimizing manœuvre 6";
-  auto const& manœuvre6 = flight_plan_->GetManœuvre(6);
+  auto const manœuvre6 = flight_plan_->GetManœuvre(6);
```
Comment (pleroy) [inline ksp_plugin_test/flight_plan_optimizer_test.cpp:422]: And this.

File: ksp_plugin_test/flight_plan_optimizer_test.cpp [hunk 11]
```diff
@@ -434,70 +400,57 @@ TEST_F(FlightPlanOptimizerTest, DISABLED_PoleTheMoon) {
...
+  EXPECT_THAT(flyby_time, ResultOf(&TTSecond, "1972-03-27T01:09:47"_DateTime));
+  EXPECT_THAT(flyby_inclination, IsNear(89.98_(1) * Degree));
+  EXPECT_EQ(34, number_of_evaluations);
   number_of_evaluations = 0;
 
   CHECK_OK(flight_plan_->Replace(manœuvre6.burn(), /*index=*/6));
 
   LOG(INFO) << "Optimizing manœuvre 7";
-  auto const& manœuvre7 = flight_plan_->GetManœuvre(7);
+  auto const manœuvre7 = flight_plan_->GetManœuvre(7);
```
Comment (pleroy) [inline ksp_plugin_test/flight_plan_optimizer_test.cpp:440]: And this.

File: ksp_plugin_test/flight_plan_optimizer_test.cpp [hunk 12]
```diff
@@ -529,25 +478,20 @@ TEST_F(FlightPlanOptimizerTest, DISABLED_Combined) {
       [&number_of_evaluations](FlightPlan const&) { ++number_of_evaluations; });
 
   LOG(INFO) << "Optimizing manœuvre 5";
-  auto const& manœuvre5 = flight_plan_->GetManœuvre(5);
+  auto const manœuvre5 = flight_plan_->GetManœuvre(5);
```
Comment (pleroy) [inline ksp_plugin_test/flight_plan_optimizer_test.cpp:481]: And this.

**Review by pleroy — APPROVED** [review]
