### PR TITLE
Parachute torque

### LINKED ISSUE #2607: Parachuting Kerbals behave unphysically in Fuchs
Noted while testing #2604; independently reported by @darthpointer.

@darthpointer further reports that the Kerbals are fine in Frobenius, so this likely has something to do with the rigidity assumptions of Fuchs, rather than improper force or torque application.

If all else fails we could make them unmanageable (parachuting leads to unmanageability by grounding in the short term anyway).

### PR DESCRIPTION
**Pull request by eggrobin**
As @ferram4 said,
> consider it all cursed.

This fixes #2607.

### CODE REVIEW

**Comment by eggrobin** [comment]
The calculations could probably gain from being done on the C++ side, but they involve only C#-side inputs, so this would have to be a free interface function that takes Δω_world, the two quaternions, and the principal moments of inertia, types all of that, multiplies the inertia tensor by Δω, and untypes and returns ΔL.

File: ksp_plugin_adapter/ksp_plugin_adapter.cs [hunk 1]
```diff
@@ -1494,8 +1513,40 @@ class PartCentredForceHolder {
...
+            // Instead of applying forces some distance from the centre of mass,
+            // or applying torques, EVA parachutes directly set the angular
+            // velocity of the Kerbal.  We register a torque equivalent to the
+            // change in angular momentum; failing to do so would cause the
+            // parachute to act on the linear motion but not the attitude,
+            // so that Kerbals would keep spinning under their parachute in
+            // stock, and would orient themselves head-down (and parachute-down)
+            // with FAR.  See #2607.
+            // To quote ferram4, “consider it all cursed”.
+            Vector3d Δω_world = part.rb.angularVelocity - old_angular_velocity;
```
Comment (pleroy) [inline ksp_plugin_adapter/ksp_plugin_adapter.cs:1530]: I think I would really prefer if this code was in C++.  It's a bit annoying to pass things through the interface and retype all the data, but we would have a better confidence that everything is correct, including when we maintain it.  It could live directly in `interface.cpp`, no point in pushing it to some class.

Comment (eggrobin) [reply ksp_plugin_adapter/ksp_plugin_adapter.cs:1530]: Done. Considering how sloppy our handling of the MTS system was, I am not sure this change is less error-prone. I tried cleaning up the existing conversion constant.

File: ksp_plugin/interface.cpp [hunk 2]
```diff
@@ -334,6 +334,48 @@ void __cdecl principia__ActivateRecorder(bool const activate) {
...
+       principal_axes_rotation,
+       part_rotation});
+  using PartPrincipalAxes = Frame<serialization::Frame::PhysicsTag,
+                                  Arbitrary,
+                                  Handedness::Left,
+                                  serialization::Frame::PRINCIPAL_AXES>;
+
+  auto const angular_velocity =
+      FromXYZ<AngularVelocity<World>>(world_angular_velocity);
+
```
Comment (pleroy) [inline ksp_plugin/interface.cpp:354]: Remove one empty line.
