### PR TITLE
Change the computation of the drag torque to have the same effect as in PhysX

### LINKED ISSUE #4166: Craft Jitters at high speed and low altitude
Only using Restock, Restock +  and Principia, on a fresh sandbox save. 

When going really fast at low altitude (speed needed depends on altitude and plane design, using a simple rapier https://imgur.com/a/mZsxA8N it starts at around 800m/s bellow 2000m and 1000m/s at 5000m) the plane and camera shakes side to side, increasing in severity with higher speed until the ship gets separated and broken. The aircraft is still a bit controllable. Video: https://imgur.com/a/rKuZTdX (warning, sudden motion)

This also happens on reentry with a rocket.

Of course if i remove principia from GameData this stops happening.

### LINKED ISSUE #4531: Possible Principia issue during reentry / vessel split: NaN velocities and vessel instability
I’m not fully sure this is a Principia-only bug, but after a lot of testing it looks like Principia is on the critical path of the failure.

My setup is KSP 1.12.5 on Windows x64, using Principia 2026041712-Lehmer. The main repro is in an RSS-based modded install, and it happens even at x1 warp.

What happens is this: during reentry, usually around vessel split or parachute deployment, the craft suddenly becomes unstable, its velocity jumps to absurd values (sometimes millions of metres per second), it gets thrown away in an apparently random direction, and then KSP starts reporting NaN collider / transform errors, sometimes recalculates the orbit to the Sun, and then freezes or crashes.

The reason I’m reporting this here is that Principia logs consistently show the failure happening around unpack / split transitions: unpacked parts appearing between `BetterLateThanNever` and `WaitForFixedUpdate`, vessel split / extraction, and repeated internal collision reports. In some reduced repros, Principia also removes the vessel as `dead, vessel is completely unfaithful`.

I’m not claiming this is definitely a Principia bug, but removing Principia makes the problem disappear on my side, while keeping it installed brings it back.

UPD: The problem was analyzed and Codex tried to solve it. I don't understand code myself, but I admit that the neural network can talk complete nonsense, but the visual description of the problem is correct.

Image

[KSP.log](https://github.com/user-attachments/files/26910638/KSP.log)
[stderr.log](https://github.com/user-attachments/files/26910639/stderr.log)
[INFO.20260420-201341.39976.log](https://github.com/user-attachments/files/26910642/INFO.20260420-201341.39976.log)
[WARNING.20260420-201341.39976.log](https://github.com/user-attachments/files/26910641/WARNING.20260420-201341.39976.log)
[ERROR.20260420-201341.39976.log](https://github.com/user-attachments/files/26910640/ERROR.20260420-201341.39976.log)

### PR DESCRIPTION
**Pull request by pleroy**
The computation of the torque is done on the C++ side in `Part` and the test is moved to `part_test.cpp`.

I tested the save in #4166 as well as the ones in #2519 and #3697.

Fix #4166.
Fix #4531.

### CODE REVIEW

File: ksp_plugin/interface_part.cpp [hunk 1]
```diff
@@ -1,27 +1,82 @@
...
+  InertiaTensor<PartPrincipalAxes> const inertia_tensor_in_principal_axes(
+      R3x3Matrix<MomentOfInertia>({moments_of_inertia.x, zero, zero},
+                                  {zero, moments_of_inertia.y, zero},
+                                  {zero, zero, moments_of_inertia.z}));
+
+  Rotation<PartPrincipalAxes, RigidPart> const principal_axes_to_part(
+      FromWXYZ(principal_axes_rotation));
+
+  return principal_axes_to_part(inertia_tensor_in_principal_axes);
+}
```
Comment (eggrobin) [inline ksp_plugin/interface_part.cpp]: Use this in `principia__InsertOrKeepLoadedPart` too (consider moving it to `interface_body` with the other conversions as needed).

File: ksp_plugin/part.hpp [hunk 2]
```diff
@@ -167,6 +169,16 @@ class Part final {
   // Returns "part name (part ID)".
   std::string ShortDebugString() const;
 
+  // Computes the torque that implements the bogus PhysX exponential decay of
+  // the angular velocity.  It is here for ease of testing.  It cannot be a
+  // method of `Part` because this is computed before the `Part` has been
+  // constructed/updated.
```
Comment (eggrobin) [inline ksp_plugin/part.hpp]:
```suggestion
  // the angular velocity.  It is here for ease of testing.  It must be static
  // because this is computed before the `Part` has been constructed/updated.
```
This is not C#, Java, or Python we don’t call member functions methods (and those languages call their equivalents of static member functions methods too anyway).

**Review by eggrobin — APPROVED** [review]

File: ksp_plugin/part.hpp (hunk 2 above)
Comment (pleroy) [reply ksp_plugin/part.hpp]: Done.

File: ksp_plugin/interface_part.cpp (hunk 1 above)
Comment (pleroy) [reply ksp_plugin/interface_part.cpp]: Done.
