### PR TITLE
Logging for DOF

### LINKED ISSUE #399: Logging for Pair
`DegreesOfFreedom` is logged nicely, but not `Pair`. When a comparison fails, things get ugly:
```
Expected: is equal to 48-byte object <00-00 00-00 00-00 35-40 00-00 00-00 00-00 36-40 00-00 00-00 00-00 37-40 00-00 00-00 00-00 38-40 00-00 00-00 00-00 39-40 00-00 00-00 00-00 3A-40>
  Actual: {{+3.10000000000000000e+01 m, +3.20000000000000000e+01 m, +3.30000000000000000e+01 m}, {+3.40000000000000000e+01 m s^-1, +3.50000000000000000e+01 m s^-1, +3.60000000000000000e+01 m s^-1}}
```

### PR DESCRIPTION
**Pull request by pleroy**
Fix #399.

### CODE REVIEW

File: physics/degrees_of_freedom_body.hpp [hunk 1]
```diff
@@ -66,6 +66,13 @@ DegreesOfFreedom<Frame> Barycentre(
   CHECK(!degrees_of_freedom.empty());
 }
 
+template<typename Frame>
+std::ostream& operator<<(std::ostream& out,
+                         DegreesOfFreedom<Frame> const& degrees_of_freedom) {
+  out << "{" << degrees_of_freedom.position() << ", "
+      << degrees_of_freedom.velocity() << "}";
+  return out;
+}
```
Comment (eggrobin) [inline physics/degrees_of_freedom_body.hpp]: newline after.
