### PR TITLE
Proper diagonalization algorithm

### LINKED ISSUE #2853: Crash while nearby vessel explodes
Encountered a crash while reentering and the nearby service module was exploding.

Error message:

```
    @   00007FFCA8316360  	google::LogMessageFatal::~LogMessageFatal [0x00007FFCA831635F+47]
    @   00007FFC62CEBCA7  	principia__VesselVelocity [0x00007FFC62CEBCA6+194918]
    @   00007FFC62CEADC3  	principia__VesselVelocity [0x00007FFC62CEADC2+191106]
    @   00007FFC62DFF33D  	principia__VesselVelocity [0x00007FFC62DFF33C+1323004]
    @   00007FFC62D09BA4  	principia__VesselVelocity [0x00007FFC62D09BA3+317539]
    @   00007FFC62DAEE9D  	principia__VesselVelocity [0x00007FFC62DAEE9C+994140]
    @   00007FFC62D2582F  	principia__VesselVelocity [0x00007FFC62D2582E+431342]
    @   00007FFCCA8714C2  	configthreadlocale [0x00007FFCCA8714C1+145]
    @   00007FFCCBA97034  	BaseThreadInitThunk [0x00007FFCCBA97033+19]
    @   00007FFCCD15D0D1  	RtlUserThreadStart [0x00007FFCCD15D0D0+32]
F0108 20:19:12.763484 14000 not_null_body.hpp:33] Check failed: other != nullptr 
```

[INFO.log](https://gist.github.com/al2me6/3495cd7d8cec13495c448724a07b62fa)

### PR DESCRIPTION
**Pull request by pleroy**
Fix #2853.

### CODE REVIEW

File: geometry/symmetric_bilinear_form_body.hpp [hunk 1]
```diff
@@ -17,13 +19,58 @@ namespace principia {
...
+struct CosSin {
+  double cos;
+  double sin;
+};
+
+// This is J(p, q, θ) in [GV13] section 8.5.1.  This matrix is also called a
+// Givens rotation.
+inline R3x3Matrix<double> JacobiRotation(int const p,
+                                         int const q,
+                                         CosSin const& cos_sin) {
```
Comment (eggrobin) [inline geometry/symmetric_bilinear_form_body.hpp:40]: Rename `cos_sin` to θ, and auto const& [c, s] = θ in the body of the function.

File: geometry/symmetric_bilinear_form_body.hpp [hunk 2]
```diff
@@ -17,13 +19,58 @@ namespace principia {
...
+  return j;
+};
+
+// See [GV13] section 8.5.2.
+template<typename Scalar>
+CosSin SymmetricShurDecomposition2(R3x3Matrix<Scalar> const& A,
+                                   int const p,
+                                   int const q) {
+  static Scalar const zero{};
+  CosSin cos_sin;
```
Comment (eggrobin) [inline geometry/symmetric_bilinear_form_body.hpp:55]: Rename this to θ for consistency with the surrounding notation in GV13, and use `auto& [c, s] = θ`.

File: geometry/symmetric_bilinear_form_body.hpp [hunk 3]
```diff
@@ -17,13 +19,58 @@ namespace principia {
...
+                                         CosSin const& cos_sin) {
+  R3x3Matrix<double> j = R3x3Matrix<double>::Identity();
+  j(p, p) = cos_sin.cos;
+  j(q, q) = cos_sin.cos;
+  j(p, q) = cos_sin.sin;
+  j(q, p) = -cos_sin.sin;
+  return j;
+};
+
+// See [GV13] section 8.5.2.
```
Comment (eggrobin) [inline geometry/symmetric_bilinear_form_body.hpp:49]: Algorithm 8.5.1 even.

File: geometry/symmetric_bilinear_form_body.hpp [hunk 4]
```diff
@@ -17,13 +19,58 @@ namespace principia {
...
+  double cos;
+  double sin;
+};
+
+// This is J(p, q, θ) in [GV13] section 8.5.1.  This matrix is also called a
+// Givens rotation.
+inline R3x3Matrix<double> JacobiRotation(int const p,
+                                         int const q,
+                                         CosSin const& cos_sin) {
+  R3x3Matrix<double> j = R3x3Matrix<double>::Identity();
```
Comment (eggrobin) [inline geometry/symmetric_bilinear_form_body.hpp:41]: J.

File: geometry/symmetric_bilinear_form_body.hpp [hunk 5]
```diff
@@ -130,88 +177,79 @@ template<typename Eigenframe>
...
+          max_p = p;
+          max_q = q;
+        }
+      }
+    }
+    if (max_Apq <= ε * frobenius_norm_of_A) {
+      break;
+    }
+
+    auto cos_sin = SymmetricShurDecomposition2(A, max_p, max_q);
```
Comment (eggrobin) [inline geometry/symmetric_bilinear_form_body.hpp:211]: auto const θ.

**Review by eggrobin — APPROVED** [review]
