### PR TITLE
Fix a bug or two with short orbit analyses

### LINKED ISSUE #2867: Hard CTD when using the slider to change the tangent after modifying the initial time using its slider.
INFO -> https://gist.github.com/daantimmer/a48d2b44437c76324bbd808e43d6493e
FATAL -> https://gist.github.com/daantimmer/f3f673a35f575b63f1406f6e0427b412

I was creating the initial flight plan of a newly launched vessel.
I first modified initial time of maneouver.
Then I tried to modify the Tangent and the moment I clicked the slider the game did a hard CTD.

### PR DESCRIPTION
**Pull request by eggrobin**
Fix #2867.

### CODE REVIEW

File: ksp_plugin/orbit_analyser.cpp [hunk 1]
```diff
@@ -120,9 +120,8 @@ Status OrbitAnalyser::AnalyseOrbit(GuardedParameters guarded_parameters) {
         parameters.extended_mission_duration.value_or(
             parameters.mission_duration),
         std::max(2 * smallest_osculating_period, parameters.mission_duration));
-    for (Instant t = parameters.first_time + analysis_duration / 0x1p10;
-         trajectory.back().time < parameters.first_time + analysis_duration;
-         t += analysis_duration / 0x1p10) {
+    for (int n = 0; n <= 0x1p10; ++n) {
```
Comment (pleroy) [inline ksp_plugin/orbit_analyser.cpp:123]: Could we invest in a constant for 1024?  This number shows up in two places.

Also, `const` the parameter at line 86 (stupid github won't let me comment there.)

**Review by pleroy — APPROVED** [review]
