### PR TITLE
#1618 is the new #1447

### LINKED ISSUE #1618: crash on minmus
I got to Minmmus, and landed. When I tried to go away from the surface, the game crashed.

Here is the glog archives: https://www.dropbox.com/s/yn3i35y8vkhn4cj/Principia.rar?dl=0

And here is the KSP.log https://www.dropbox.com/s/lq9jcl4o4m72yiw/KSP.rar?dl=0

### PR DESCRIPTION
**Pull request by eggrobin**
Fix #1618.

We don't have a save, so this is not tested, but the trace looks similar enough to #1447 that we can reasonably guess that this is the issue.

### CODE REVIEW

File: ksp_plugin_adapter/ksp_plugin_adapter.cs [hunk 1]
```diff
@@ -1206,18 +1206,18 @@ private System.Collections.IEnumerator
                 closest_physical_parent(part1).flightID);
           }
           foreach (var collider in part1.currentCollisions) {
-            if (collider.gameObject.layer == (int)UnityLayers.LocalScenery) {
-              Log.Info("Reporting collision with local scenery " +
-                       collider.name);
-              plugin_.ReportGroundCollision(
-                  closest_physical_parent(part1).flightID);
-            }
```
Comment (pleroy) [inline ksp_plugin_adapter/ksp_plugin_adapter.cs]: This code was odd: let's use `collider` and later check if by any chance it was null...
