### PR TITLE
Don't try to render markers related to the target vessel when the target vessel does not exist

### LINKED ISSUE #3636: Crash when in TKO reference frame and the target vessel is destroyed
I was targeted onto the "Rock Grabber", in map view in the TKO reference frame and executing a planned manouever from the flight planner with the flight planner window open, when the game crashed. Logs appear to show that the vessel I  was targetting was destroyed, triggering the crash:

```
I0513 12:40:43.089469  8160 plugin.cpp:581] Removing vessel Rock Grabber (1f1f0dbd-7ed9-4ad4-9935-b51317aa17ab)
I0513 12:40:43.089469  8160 vessel.cpp:92] Destroying vessel Rock Grabber (1f1f0dbd-7ed9-4ad4-9935-b51317aa17ab)
I0513 12:40:43.102401  8160 part.cpp:62] Destroying part probeStackSmall (33DADDFD)
I0513 12:40:43.102401  8160 part.cpp:62] Destroying part nuclearEngine (48CC3DDD)
I0513 12:40:43.102401  8160 part.cpp:62] Destroying part batteryBank (CACC85B3)
I0513 12:40:43.102401  8160 part.cpp:62] Destroying part MK1Fuselage (9F532475)
I0513 12:40:43.102401  8160 part.cpp:62] Destroying part PotatoRoid (9FD2326B)
I0513 12:40:43.102401  8160 part.cpp:62] Destroying part GrapplingDevice (919AB656)
I0513 12:40:43.102401  8160 part.cpp:62] Destroying part RCSFuelTank (0AEB9246)
I0513 12:40:43.102401  8160 part.cpp:62] Destroying part advSasModule (63A5473F)
I0513 12:40:43.102401  8160 part.cpp:62] Destroying part MK1Fuselage (E9340D1C)
I0513 12:40:43.102401  8160 pile_up.cpp:94] Destroying pile up at 0000015D778892E0
    @   00007FF9E03644FF  	google::LogMessageFatal::~LogMessageFatal [0x00007FF9E03644FE+46]
    @   00007FF991CA69D9  	principia__VesselVelocity [0x00007FF991CA69D8+1245224]
    @   00007FF991B7273E  	principia__RenderedPredictionClosestApproaches [0x00007FF991B7273D+573]
    @   0000015C61A720EA  	(No symbol) [0x0000015C61A720E9]
F0513 12:40:43.139051  8160 plugin.cpp:1019] Check failed: renderer_->HasTargetVessel() 
```

### PR DESCRIPTION
**Pull request by pleroy**
Fix #3636.

### CODE REVIEW

File: ksp_plugin_adapter/ksp_plugin_adapter.cs [hunk 1]
```diff
@@ -386,6 +386,24 @@ class PartCentredForceHolder {
...
+    if (target_id != null && plugin_.HasVessel(target_id)) {
+      return target;
+    } else {
+      return null;
+    }
+  }
+
+  // Same as above but returns the GUID.
+  private string TargetVesselGuid() {
+    return TargetVessel().id.ToString();
```
Comment (eggrobin) [inline ksp_plugin_adapter/ksp_plugin_adapter.cs:403]: This throws NullReferenceException if `TargetVessel()` is null; did you mean `TargetVessel()?.id.ToString()`?

**Review by eggrobin — CHANGES_REQUESTED** [review]

**Review by eggrobin — APPROVED** [review]
