### PR TITLE
libc++ version and removal of 32-bit support

### LINKED ISSUE #1627: FAQ incorrect regarding libc++ and libc++abi?
The FAQ states that for Linux "You need libc++ and libc++abi 3.5-2."
In Debian Stable the libc++ 3.5-2 did not have the shared_mutex and some other functions. Using 4.0.1-2 from unstable did however work.

Is the FAQ outdated or do the libc++ 3.5-2 differ between Debian and Ubuntu?

### PR DESCRIPTION
**Pull request by pleroy**
Fix #1627.

### CODE REVIEW

File: ksp_plugin_adapter/loader.cs [hunk 1]
```diff
@@ -24,13 +24,12 @@ internal static class Loader {
     switch (Environment.OSVersion.Platform) {
       case PlatformID.Win32NT:
         can_determine_cxx_installed = true;
-        is_cxx_installed = () => IsVCRedistInstalled(is_32_bit);
+        is_cxx_installed = () => IsVCRedistInstalled();
```
Comment (eggrobin) [inline ksp_plugin_adapter/loader.cs]: does `is_cxx_installed = IsVCRedistInstalled;` work?
