### PR TITLE
Dynamic frame validity interval

### LINKED ISSUE #1511: Crash in PlotMethod0
```
Log file created at: 2017/08/06 16:03:14
Running on machine: BELLINI
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
    @   000007FEE5D8E959        google::LogMessageFatal::~LogMessageFatal [0x000007FEE5D8E958+104] (c:\users\robin\projects\kerbal space program\plugins\google\glog\src\logging
.cc:2034)
    @   000007FEE5CAFEC6        principia::physics::internal_discrete_trajectory::DiscreteTrajectory<principia::geometry::internal_frame::Frame<enum principia::serialization::F
rame_PluginTag,7,1> >::GetInterpolation [0x000007FEE5CAFEC5+229] (c:\users\robin\projects\kerbal space program\plugins\principia\physics\discrete_trajectory_body.hpp:322)
    @   000007FEE5CACA7C        principia::physics::internal_discrete_trajectory::DiscreteTrajectory<principia::geometry::internal_frame::Frame<enum principia::serialization::F
rame_PluginTag,7,1> >::EvaluateDegreesOfFreedom [0x000007FEE5CACA7B+91] (c:\users\robin\projects\kerbal space program\plugins\principia\physics\discrete_trajectory_body.hpp:209
)
    @   000007FEE5CB3B05        principia::physics::internal_body_centred_body_direction_dynamic_frame::BodyCentredBodyDirectionDynamicFrame<principia::geometry::internal_frame
::Frame<enum principia::serialization::Frame_PluginTag,7,1>,principia::geometry::internal_frame::Frame<enum pri [0x000007FEE5CB3B04+84] (c:\users\robin\projects\kerbal space pr
ogram\plugins\principia\physics\body_centred_body_direction_dynamic_frame_body.hpp:83)
    @   000007FEE5D1DA5A        principia::ksp_plugin::internal_planetarium::Planetarium::ComputePlottableSegments [0x000007FEE5D1DA59+265] (c:\users\robin\projects\kerbal spac
e program\plugins\principia\ksp_plugin\planetarium.cpp:269)
    @   000007FEE5D1C085        principia::ksp_plugin::internal_planetarium::Planetarium::PlotMethod0 [0x000007FEE5D1C084+212] (c:\users\robin\projects\kerbal space program\plu
gins\principia\ksp_plugin\planetarium.cpp:45)
    @   000007FEE5D1C667        principia::ksp_plugin::internal_planetarium::Planetarium::PlotMethod1 [0x000007FEE5D1C666+134] (c:\users\robin\projects\kerbal space program\plu
gins\principia\ksp_plugin\planetarium.cpp:93)
    @   000007FEE5CF5BCA        principia::interface::`anonymous namespace'::PlotMethodN [0x000007FEE5CF5BC9+233] (c:\users\robin\projects\kerbal space program\plugins\principi
a\ksp_plugin\interface_planetarium.cpp:54)
    @   000007FEE5CF6AA8        principia__PlanetariumPlotPsychohistory [0x000007FEE5CF6AA7+423] (c:\users\robin\projects\kerbal space program\plugins\principia\ksp_plugin\inte
rface_planetarium.cpp:196)
    @   0000000013CE3586        (No symbol) [0x0000000013CE3585]
F0806 16:03:14.847744 13816 discrete_trajectory_body.hpp:322] Check failed: t_min() <= time (+6.00259999999744082e+02 s vs. +4.07079999999919721e+02 s)
```

### PR DESCRIPTION
**Pull request by eggrobin**
Fix #1511.

### CODE REVIEW

File: ksp_plugin/planetarium.cpp [hunk 1]
```diff
@@ -134,21 +139,21 @@ RP2Lines<Length, Camera> Planetarium::PlotMethod2(
...
 
   double const tan²_angular_resolution =
       Pow<2>(parameters_.tan_angular_resolution_);
   auto const plottable_spheres = ComputePlottableSpheres(now);
   auto const& trajectory = *begin.trajectory();
-  auto const final_time = last.time();
-
-  auto previous_time = begin.time();
+  auto const final_time = std::min(last.time(), plotting_frame_->t_max());
+  auto previous_time = std::max(begin.time(), plotting_frame_->t_min());
```
Comment (pleroy) [inline ksp_plugin/planetarium.cpp]: It seems that a similar fix should be applied to the other plot methods.
