### PR TITLE
Change IsNear to take an ApproximateQuantity and fix \o/ all the tests

### LINKED ISSUE #2269: User-defined literal to express accuracy in tests

### PR DESCRIPTION
**Pull request by pleroy**
Fix #2269.

### CODE REVIEW

File: integrators/symplectic_runge_kutta_nyström_integrator_test.cpp [hunk 1]
```diff
@@ -49,6 +50,7 @@ using testing_utilities::IsNear;
 using testing_utilities::PearsonProductMomentCorrelationCoefficient;
 using testing_utilities::Slope;
 using testing_utilities::VanishesBefore;
+using testing_utilities::operator""_⑴;
```
Comment (eggrobin) [inline integrators/symplectic_runge_kutta_nyström_integrator_test.cpp]: Unused using.

File: integrators/symplectic_runge_kutta_nyström_integrator_test.cpp [hunk 2]
```diff
@@ -11,6 +11,7 @@
 #include "integrators/symplectic_partitioned_runge_kutta_integrator.hpp"
 #include "quantities/quantities.hpp"
 #include "testing_utilities/almost_equals.hpp"
+#include "testing_utilities/approximate_quantity.hpp"
```
Comment (eggrobin) [inline integrators/symplectic_runge_kutta_nyström_integrator_test.cpp]: Unused include.

File: integrators/symmetric_linear_multistep_integrator_test.cpp [hunk 3]
```diff
@@ -52,6 +53,7 @@ using testing_utilities::PearsonProductMomentCorrelationCoefficient;
 using testing_utilities::RelativeError;
 using testing_utilities::Slope;
 using testing_utilities::VanishesBefore;
+using testing_utilities::operator""_⑴;
```
Comment (eggrobin) [inline integrators/symmetric_linear_multistep_integrator_test.cpp]: Unused using.

File: integrators/symmetric_linear_multistep_integrator_test.cpp [hunk 4]
```diff
@@ -12,6 +12,7 @@
 #include "mathematica/mathematica.hpp"
 #include "quantities/quantities.hpp"
 #include "testing_utilities/almost_equals.hpp"
+#include "testing_utilities/approximate_quantity.hpp"
```
Comment (eggrobin) [inline integrators/symmetric_linear_multistep_integrator_test.cpp]: Unused include.
