### PR TITLE
Retrobop

### LINKED ISSUE #631: Bug reported by mhoram-kerbin
Bug report by @mhoram-kerbin, [including INFO log](https://gist.github.com/mhoram-kerbin/cb302c742b6ce91504dc).
Stacktrace, to be decoded:
```
    @   64D19399  	principia__SayHello [0x64D19398+360744]
    @   64D0456F  	principia__SayHello [0x64D0456E+275198]
    @   64CF9EEA  	principia__SayHello [0x64CF9EE9+232569]
    @   64CFB757  	principia__SayHello [0x64CFB756+238822]
    @   64CF1F18  	principia__SayHello [0x64CF1F17+199847]
    @   64CEF20C  	principia__SayHello [0x64CEF20B+188315]
    @   64CEF31A  	principia__SayHello [0x64CEF319+188585]
    @   64CE8ED3  	principia__SayHello [0x64CE8ED2+162914]
    @   64CE33F5  	principia__SayHello [0x64CE33F4+139652]
    @   64CBF891  	principia__AdvanceTime [0x64CBF890+80]
F0827 20:37:08.580535 27716 continuous_trajectory_body.hpp:346] Check failed: adjusted_tolerance_ < 1E6 * previous_adjusted_tolerance (+2.07970750065819120e+04 m vs. +8.36760047436097011e+03 m) Apocalypse occurred at +3.69360002000000002e+06 s, displacements are: {+2.00014081136158829e+10 m, +6.22684278540717239e+10 m, +5.16749613391143858e+08 m} {+1.99879834252745056e+10 m, +6.22796599512423477e+10 m, +5.17017022493503511e+08 m} {+1.99739502453383179e+10 m, +6.22907864793080597e+10 m, +5.17284493047730446e+08 m} {+1.99593192770084915e+10 m, +6.23017325059046860e+10 m, +5.17551811048148572e+08 m} {+1.99441220020342484e+10 m, +6.23124374580687790e+10 m, +5.17818713204804718e+08 m} {+1.99284043447352982e+10 m, +6.23228730581115799e+10 m, +5.18084809048591316e+08 m} {+1.99122072635346756e+10 m, +6.23330816137687073e+10 m, +5.18349165468758583e+08 m} {+1.98954546813748512e+10 m, +6.23433683762633743e+10 m, +5.18605943136402369e+08 m} {+1.98700990129785919e+10 m, +6.23583748846784897e+10 m, +5.18330642157473266e+08 m}, velocities are: {-4.86010381727614094e+03 m s^-1, +4.16994503606722628e+03 m s^-1, +9.90059283069209357e+01 m s^-1} {-5.08477531697844461e+03 m s^-1, +4.14530726333875737e+03 m s^-1, +9.90638698926969283e+01 m s^-1} {-5.30951147166898136e+03 m s^-1, +4.09186631483063866e+03 m s^-1, +9.90493098011526172e+01 m s^-1} {-5.52626364447118794e+03 m s^-1, +4.01245881114019585e+03 m s^-1, +9.89481211891008172e+01 m s^-1} {-5.72804405192298418e+03 m s^-1, +3.91519902359158186e+03 m s^-1, +9.87347519128410767e+01 m s^-1} {-5.91179892346620181e+03 m s^-1, +3.81684176446339870e+03 m s^-1, +9.83259207618487068e+01 m s^-1} {-6.08704133771054694e+03 m s^-1, +3.75811478870737210e+03 m s^-1, +9.73005382853895640e+01 m s^-1} {-6.38075126868301686e+03 m s^-1, +3.96375968253334349e+03 m s^-1, +9.00137943389807020e+01 m s^-1} {-1.09163845788669951e+04 m s^-1, +6.28249524832451243e+03 m s^-1, -1.99108893076852610e+02 m s^-1}
```

### PR DESCRIPTION
**Pull request by eggrobin**
Fix #631.
Since no suitable resonance was found for the inner Jool system (the mean motion ratios were instead set to 1:4/φ:16/φ<sup>2</sup>), make Bop interesting by putting it in a highly-precessing retrograde orbit (see https://goo.gl/photos/xXh83HTejv8vo8daA for a study of the evolution of the system over a century).
Thanks to Scott Manley and @pdn4kd for suggesting a retrograde Bop, and to Scott for pointing out that this would insulate it dynamically.
Also fix an issue where tidally-locked bodies would periodically despin and spin back up in the opposite direction.

### CODE REVIEW

File: ksp_plugin_adapter/ksp_plugin_adapter.cs [hunk 1]
```diff
@@ -1367,6 +1370,96 @@ where is_in_physics_bubble(vessel)
...
   }
 
+  private void RemoveBuggyTidalLocking() {
+    ApplyToBodyTree(body => body.tidallyLocked = false);
+  }
+
+  // Deals with issue #631, unstability of the Jool system's resonance.
+  private void Fix631() {
+    // Check whether this looks like stock.
+    if (FlightGlobals.Bodies.Count < 14) {
```
Comment (pleroy) [inline ksp_plugin_adapter/ksp_plugin_adapter.cs]: Shouldn't this be 15?  Line 1393 references [14].

File: ksp_plugin_adapter/ksp_plugin_adapter.cs [hunk 2]
```diff
@@ -1367,6 +1370,96 @@ where is_in_physics_bubble(vessel)
...
+    is_stock &= (float)mean_longitude(laythe) == 3.14f;
+    is_stock &= (float)mean_longitude(vall)   == 0.9f;
+    is_stock &= (float)mean_longitude(tylo)   == 3.14f;
+    if (!is_stock) {
+      return;
+    }
+    unmodified_orbits_[vall] = new Orbit(
+        vall.orbit.inclination,
+        vall.orbit.eccentricity,
+        laythe.orbit.semiMajorAxis * Math.Pow(2.472135954999579, 2.0 / 3.0),
```
Comment (pleroy) [inline ksp_plugin_adapter/ksp_plugin_adapter.cs]: Are you sure you don't want to compute this number offline?  It could be sensitive to changes in Pow.

File: ksp_plugin_adapter/ksp_plugin_adapter.cs [hunk 3]
```diff
@@ -1367,6 +1370,96 @@ where is_in_physics_bubble(vessel)
...
+    is_stock &= (float)laythe.orbit.inclination == 0f;
+    is_stock &= (float)vall.orbit.inclination   == 0f;
+    is_stock &= (float)tylo.orbit.inclination   == 0.025f;
+    is_stock &= (float)mean_longitude(laythe) == 3.14f;
+    is_stock &= (float)mean_longitude(vall)   == 0.9f;
+    is_stock &= (float)mean_longitude(tylo)   == 3.14f;
+    if (!is_stock) {
+      return;
+    }
+    unmodified_orbits_[vall] = new Orbit(
```
Comment (pleroy) [inline ksp_plugin_adapter/ksp_plugin_adapter.cs]: This is really the modified orbits, right?  A comment would help.

File: ksp_plugin_adapter/ksp_plugin_adapter.cs [hunk 4]
```diff
@@ -1367,6 +1370,96 @@ where is_in_physics_bubble(vessel)
...
+        new Orbit(180.0 - bop.orbit.inclination,
+                  bop.orbit.eccentricity,
+                  pol.orbit.semiMajorAxis * Math.Pow(0.7, 2.0 / 3.0),
+                  bop.orbit.LAN,
+                  bop.orbit.argumentOfPeriapsis,
+                  bop.orbit.meanAnomalyAtEpoch,
+                  bop.orbit.epoch,
+                  jool);
+    // Keep the rotation of vall and tylo equal to their orbital period.
+    foreach (CelestialBody body in new CelestialBody[]{vall, tylo}) {
```
Comment (pleroy) [inline ksp_plugin_adapter/ksp_plugin_adapter.cs]: Why not bop?

File: physics/ksp_system_test.cpp [hunk 5]
```diff
@@ -0,0 +1,469 @@
...
+        +1.22173047639603061e+00 * Radian;
+    moho.elements.argument_of_periapsis = +2.61799387799149408e-01 * Radian;
+    moho.elements.mean_anomaly = +3.14000010490416992e+00 * Radian;
+  }
+
+  not_null<std::unique_ptr<Ephemeris<KSP>>> MakeEphemeris() {
+    HierarchicalSystem<KSP> hierarchical_system(std::move(sun.owned_body));
+    for (auto const celestial : planets_and_moons) {
+      hierarchical_system.Add(std::move(celestial->owned_body),
+                 celestial->parent->body,
```
Comment (pleroy) [inline physics/ksp_system_test.cpp]: Bad indent.

File: physics/ksp_system_test.cpp [hunk 6]
```diff
@@ -0,0 +1,469 @@
...
+    return make_not_null_unique<Ephemeris<KSP>>(
+        std::move(barycentric_system.bodies),
+        std::move(barycentric_system.degrees_of_freedom),
+        ksp_epoch,
+        integrators::McLachlanAtela1992Order5Optimal<Position<KSP>>(),
+        45 * Minute,
+        1 * Milli(Metre));
+  }
+
+  Instant const ksp_epoch;
```
Comment (pleroy) [inline physics/ksp_system_test.cpp]: Could we put a trailing _ for the member variables?  VS should be able to help with the renaming.

File: physics/ksp_system_test.cpp [hunk 7]
```diff
@@ -0,0 +1,469 @@
...
+  KSPCelestial dres;
+  KSPCelestial duna;
+  KSPCelestial ike;
+  KSPCelestial kerbin;
+  KSPCelestial minmus;
+  KSPCelestial mun;
+  KSPCelestial eve;
+  KSPCelestial gilly;
+  KSPCelestial moho;
+  std::vector<not_null<KSPCelestial*>> const all_bodies = {&sun,
```
Comment (pleroy) [inline physics/ksp_system_test.cpp]: Could this be sun + planets_and_moon somehow?

File: physics/ksp_system_test.cpp [hunk 8]
```diff
@@ -0,0 +1,469 @@
...
+#if NDEBUG
+#if 0
+  auto const a_century_hence = ksp_epoch + 100 * JulianYear;
+#else  // A small century so the tests don't take too long.
+  auto const a_century_hence = ksp_epoch + 5 * JulianYear;
+#endif
+
+  LOG(INFO) << "Starting integration";
+  ephemeris->Prolong(a_century_hence);
+  LOG(INFO) << "Done";
```
Comment (pleroy) [inline physics/ksp_system_test.cpp]: "Integration done"

File: physics/ksp_system_test.cpp [hunk 9]
```diff
@@ -0,0 +1,469 @@
...
+    auto const degrees_of_freedom = [t, &ephemeris](
+        KSPCelestial const& celestial) {
+      return ephemeris->trajectory(celestial.body)->
+                 EvaluateDegreesOfFreedom(t, /*hint=*/nullptr);
+    };
+    auto const jool_position = position(jool);
+
+    for (auto const* moon : moons) {
+      Length const separation = (jool_position - position(*moon)).Norm();
+      Sign separation_change = Sign(separation - last_separations[moon]);
```
Comment (pleroy) [inline physics/ksp_system_test.cpp]: const

File: physics/ksp_system_test.cpp [hunk 10]
```diff
@@ -0,0 +1,469 @@
...
+      bop_jacobi_inclinations_in_degrees.emplace_back(
+          bop_jacobi_elements.inclination / Degree);
+      bop_jacobi_nodes_in_degrees.emplace_back(
+          bop_jacobi_elements.longitude_of_ascending_node / Degree);
+      bop_jacobi_arguments_of_periapsis_in_degrees.emplace_back(
+          bop_jacobi_elements.argument_of_periapsis / Degree);
+    }
+  }
+
+  auto const fill_positions = [this, &ephemeris, &jool_system](
```
Comment (pleroy) [inline physics/ksp_system_test.cpp]: Please turn this into a bona-fide function in the fixture class.  Too big to lambda.

File: physics/ksp_system_test.cpp [hunk 11]
```diff
@@ -0,0 +1,469 @@
...
+                                                                  &ike,
+                                                                  &kerbin,
+                                                                  &minmus,
+                                                                  &mun,
+                                                                  &eve,
+                                                                  &gilly,
+                                                                  &moho};
+};
+
+TEST_F(KSPSystemTest, KerbalSystem) {
```
Comment (pleroy) [inline physics/ksp_system_test.cpp]: This test has no expectations whatsoever.  Could we add a few to make sure that things make sense (eg, the bodies remain reasonably close to one another).  Doesn't need to be very tight, but it should fail if we have a major regression.

File: ksp_plugin_adapter/ksp_plugin_adapter.cs (hunk 1 above)
Comment (eggrobin) [inline ksp_plugin_adapter/ksp_plugin_adapter.cs]: Done.

File: ksp_plugin_adapter/ksp_plugin_adapter.cs (hunk 2 above)
Comment (eggrobin) [inline ksp_plugin_adapter/ksp_plugin_adapter.cs]: If the standard math libraries of .NET change, then so will KSP's semimajor axis to period computation, so I wouldn't worry about that.

File: physics/ksp_system_test.cpp (hunk 7 above)
Comment (eggrobin) [inline physics/ksp_system_test.cpp]: Not elegantly, at least not until C++17 and ranges

File: ksp_plugin_adapter/ksp_plugin_adapter.cs (hunk 3 above)
Comment (eggrobin) [inline ksp_plugin_adapter/ksp_plugin_adapter.cs]: commented.

File: ksp_plugin_adapter/ksp_plugin_adapter.cs (hunk 4 above)
Comment (eggrobin) [inline ksp_plugin_adapter/ksp_plugin_adapter.cs]: commented at length.

File: physics/ksp_system_test.cpp (hunk 5 above)
Comment (eggrobin) [inline physics/ksp_system_test.cpp]: Done.

File: physics/ksp_system_test.cpp (hunk 6 above)
Comment (eggrobin) [inline physics/ksp_system_test.cpp]: Done.

File: physics/ksp_system_test.cpp (hunk 8 above)
Comment (eggrobin) [inline physics/ksp_system_test.cpp]: Done.

File: physics/ksp_system_test.cpp (hunk 9 above)
Comment (eggrobin) [inline physics/ksp_system_test.cpp]: Done.

File: physics/ksp_system_test.cpp (hunk 10 above)
Comment (eggrobin) [inline physics/ksp_system_test.cpp]: Grump.

File: physics/ksp_system_test.cpp (hunk 11 above)
Comment (eggrobin) [inline physics/ksp_system_test.cpp]: Done.
