### PR TITLE
Do not forget the past of histories if that would destroy flight plans

### LINKED ISSUE #872: Crash reported by maccollo
FATAL:
```
Log file created at: 2016/02/11 21:50:46
Running on machine: DESKTOP-JDS1DLG
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
    @   8D764D4C  	(No symbol) [0x8D764D4B]
    @   8D713F20  	(No symbol) [0x8D713F1F]
    @   8D72664F  	(No symbol) [0x8D72664E]
    @   8D6863A1  	(No symbol) [0x8D6863A0]
    @   8D68A12E  	(No symbol) [0x8D68A12D]
    @   8D69568F  	(No symbol) [0x8D69568E]
F0211 21:50:46.492843 10980 continuous_trajectory_body.hpp:187] Check failed: t_min() <= time (+3.61430815794418042e+05 s vs. +3.61430577978739981e+05 s) 
```

### PR DESCRIPTION
**Pull request by pleroy**
Fixes #872.  Added a check so that similar bugs would be easier to detect in the future.

### CODE REVIEW

File: physics/discrete_trajectory_body.hpp [hunk 1]
```diff
@@ -56,10 +56,9 @@ DiscreteTrajectory<Frame>::~DiscreteTrajectory() {
   }
 }
 
-template<typename Frame>
+template <typename Frame>
```
Comment (eggrobin) [inline physics/discrete_trajectory_body.hpp]: blarg.
