### PR TITLE
Fix problems with the Linux build.

### LINKED ISSUE #1445: ElementaryFunctionsTest.ExpLogAndRoots fails on Linux
```
quantities/elementary_functions_test.cpp:188: Failure
      Expected: std::exp(std::log(Gallon / Pow<3>(Foot)) / 3) * Foot
      Which is: +1.65658100184054802e-01 m
To be equal to: Cbrt(Gallon)
      Which is: +1.65658100184054774e-01 m
[  FAILED  ] ElementaryFunctionsTest.ExpLogAndRoots (0 ms)
```

### LINKED ISSUE #1446: The Linux build should produce a .tar.gz file, not a .gz file
Otherwise everything gets concatenated in a single file.

### PR DESCRIPTION
**Pull request by pleroy**
Fix #1445.  Fix #1446.

### CODE REVIEW

File: quantities/elementary_functions_test.cpp [hunk 1]
```diff
@@ -184,8 +184,12 @@ TEST_F(ElementaryFunctionsTest, HyperbolicFunctions) {
...
   EXPECT_THAT(std::exp(std::log(2) / 2), AlmostEquals(Sqrt(2), 1));
   EXPECT_THAT(std::exp(std::log(2) / 3), AlmostEquals(Cbrt(2), 1));
-  EXPECT_EQ(std::exp(std::log(Rood / Pow<2>(Foot)) / 2) * Foot, Sqrt(Rood));
-  EXPECT_EQ(std::exp(std::log(Gallon / Pow<3>(Foot)) / 3) * Foot, Cbrt(Gallon));
+  EXPECT_THAT(
+      Sqrt(Rood),
+      AlmostEquals(std::exp(std::log(Rood / Pow<2>(Foot)) / 2) * Foot, 0));
+  EXPECT_THAT(
+      Cbrt(Gallon),
+      AlmostEquals(std::exp(std::log(Gallon / Pow<3>(Foot)) / 3) * Foot, 0, 1));
```
Comment (eggrobin) [inline quantities/elementary_functions_test.cpp]: Swap the order of actual/expected (cf. the first two expectations).

Comment (pleroy) [inline quantities/elementary_functions_test.cpp]: As discussed, this is fine.
